load("@rules_xcodeproj//xcodeproj:defs.bzl", "top_level_target", "xcodeproj")

# `bazel run //:xcodeproj` generates RickAndMortyMigration.xcodeproj.
xcodeproj(
    name = "xcodeproj",
    project_name = "RickAndMortyMigration",
    tags = ["manual"],
    top_level_targets = [
        top_level_target(
            "//App:RickAndMorty",
            target_environments = ["simulator"],
        ),
        "//Features/Characters:CharactersTests",
        "//Features/Episodes:EpisodesTests",
        "//Features/Locations:LocationsTests",
    ],
)
