#!/usr/bin/env bash
# Regenerates apollo/private/versions.bzl from the GitHub releases of the
# apollo-ios-dev fork. Skips draft releases (their assets are not publicly
# downloadable) and fork-only tags with no upstream Apollo iOS release.
#
# Usage: tools/update_versions.sh [owner/repo]
set -euo pipefail

REPO="${1:-erneestoc/apollo-ios-dev}"
# Fork-only tags: there is no Apollo iOS runtime to pair them with.
SKIP_TAGS=" 1.15.4 "
OUT="$(cd "$(dirname "$0")/.." && pwd)/apollo/private/versions.bzl"

{
  echo '"""Generated by tools/update_versions.sh. Do not edit."""'
  echo
  echo "APOLLO_CLI_REPO = \"${REPO}\""
  echo
  echo "# version -> { rust target triple -> sha256 of apollo-ios-cli-<triple>.tar.gz }"
  echo "APOLLO_CLI_VERSIONS = {"
  gh release list -R "$REPO" -L 200 --json tagName,isDraft \
    --jq '.[] | select(.isDraft | not) | .tagName' |
    sort -t. -k1,1n -k2,2n -k3,3n |
    while read -r tag; do
      [[ "$SKIP_TAGS" == *" $tag "* ]] && continue
      echo "    \"${tag}\": {"
      gh release view "$tag" -R "$REPO" --json assets \
        --jq '.assets[] | select(.name | endswith(".tar.gz")) | "\(.name) \(.digest)"' |
        sort |
        while read -r name digest; do
          triple="${name#apollo-ios-cli-}"
          triple="${triple%.tar.gz}"
          echo "        \"${triple}\": \"${digest#sha256:}\","
        done
      echo "    },"
    done
  echo "}"
} > "$OUT"

echo "wrote $OUT"
