"""apollo_operations: generates one framework's operations and fragments."""

load(":config.bzl", "codegen_config")
load(":providers.bzl", "ApolloOperationsInfo", "ApolloSchemaInfo")
load(":sources.bzl", "generated_swift_sources", "module_placeholder")
load(":toolchain.bzl", "APOLLO_TOOLCHAIN_TYPE", "resolve_cli_for_schema")
load(":worker.bzl", "codegen_args", "codegen_execution_requirements", "worker_env")

_IMPORTS = """\
// @generated
// This file was automatically generated by rules_apollo for {label}.
//
// Operations here use fragments defined in these modules. An @_exported import in
// one file makes the module visible to every file of this module.

{imports}
"""

def _apollo_operations_impl(ctx):
    schema = ctx.attr.schema[ApolloSchemaInfo]
    srcs = ctx.files.srcs

    cli = resolve_cli_for_schema(ctx, schema)
    module_name = ctx.attr.module_name or ctx.label.name

    for dep in ctx.attr.deps:
        dep_schema = dep[ApolloOperationsInfo].schema
        if dep_schema != schema.label:
            fail("%s uses schema %s but dep %s uses %s. Operations can only use fragments from the same schema." %
                 (ctx.label, schema.label, dep.label, dep_schema))

    transitive_srcs = depset(srcs, transitive = [d[ApolloOperationsInfo].transitive_srcs for d in ctx.attr.deps])

    out = ctx.actions.declare_directory(ctx.label.name + "_operations")
    args = codegen_args(
        ctx,
        config = codegen_config(
            schema.config,
            schema.schema_files.to_list(),
            transitive_srcs.to_list(),
            access_modifier = ctx.attr.access_modifier,
        ),
        output_dir = out,
        mode = "operations",
        generate_for = srcs,
    )
    ctx.actions.run(
        executable = cli.cli,
        arguments = [args],
        inputs = depset(transitive = [schema.schema_files, transitive_srcs]),
        outputs = [out],
        mnemonic = "ApolloCodegen",
        progress_message = "Generating Apollo operations %{label}",
        execution_requirements = codegen_execution_requirements(),
        env = worker_env(schema.label),
        toolchain = None if schema.cli_override else APOLLO_TOOLCHAIN_TYPE,
    )

    outputs = [generated_swift_sources(ctx, out)]
    if ctx.attr.deps:
        imports = ctx.actions.declare_file(ctx.label.name + "_ApolloImports.swift")
        ctx.actions.write(imports, _IMPORTS.format(
            label = ctx.label,
            imports = "\n".join(sorted({
                "@_exported import " + d[ApolloOperationsInfo].module_name: True
                for d in ctx.attr.deps
            }.keys())),
        ))
        outputs.append(imports)
    else:
        # Without `deps` there is no imports file, and `srcs` can generate nothing (e.g. none).
        outputs.append(module_placeholder(ctx))

    return [
        DefaultInfo(files = depset(outputs)),
        OutputGroupInfo(generated_tree = depset([out])),
        ApolloOperationsInfo(
            schema = schema.label,
            module_name = module_name,
            srcs = depset(srcs),
            transitive_srcs = transitive_srcs,
        ),
    ]

apollo_operations = rule(
    implementation = _apollo_operations_impl,
    doc = """Generates Swift for the operations and fragments in `srcs`.

Inputs are `srcs` plus the `.graphql` files of `deps` (so their fragments resolve),
never the whole app. Code is generated only for `srcs` (`--bazel-generate-for`);
fragments from `deps` are imported from their modules. The generated code imports the schema module
(`schema_namespace`).

Runs on the same persistent worker as its schema, which keeps the parsed schema in
memory, so each target only pays for compiling its own operations.""",
    attrs = {
        "schema": attr.label(
            mandatory = True,
            providers = [ApolloSchemaInfo],
            doc = "The apollo_schema to generate against. Its CLI and options are used.",
        ),
        "srcs": attr.label_list(
            allow_files = [".graphql"],
            doc = "Operations and fragments owned by this module.",
        ),
        "deps": attr.label_list(
            providers = [ApolloOperationsInfo],
            doc = "Other apollo_operations whose fragments these operations use.",
        ),
        "module_name": attr.string(
            doc = "Swift module the generated code is compiled into. Defaults to the target name.",
        ),
        "access_modifier": attr.string(
            default = "public",
            values = ["public", "internal"],
            doc = "Access modifier of the generated operations and fragments.",
        ),
    },
    provides = [ApolloOperationsInfo],
    toolchains = [config_common.toolchain_type(APOLLO_TOOLCHAIN_TYPE, mandatory = False)],
)
