"""Providers shared by the rules_apollo rules."""

ApolloCliInfo = provider(
    doc = "An apollo-ios-cli binary and the Apollo iOS version it generates code for.",
    fields = {
        "cli": "FilesToRunProvider: the apollo-ios-cli executable.",
        "version": "string: the Apollo iOS version, e.g. \"2.4.0\".",
    },
)

ApolloSchemaInfo = provider(
    doc = """A GraphQL schema plus the codegen configuration shared by every target generated against it.

Operation targets take their configuration and Apollo version from this provider
instead of declaring their own, so a schema and all of its operation modules are
always generated by the same apollo-ios-cli version with the same options.""",
    fields = {
        "label": "Label of the apollo_schema target. Also keys the persistent worker.",
        "namespace": "string: schemaNamespace, which is also the Swift module of the schema types.",
        "schema_files": "depset[File]: .graphqls / .json schema files.",
        "operation_files": "depset[File]: every .graphql of the app (the schema's srcs). Test mocks compile these.",
        "config": "dict: codegen configuration without `input`/`output`; JSON-encodable.",
        "version": "string: Apollo iOS version the schema was generated with. Operations must match it.",
        "cli_override": "ApolloCliInfo from the schema's `cli` attr, or None if it used the toolchain.",
    },
)

ApolloOperationsInfo = provider(
    doc = "GraphQL operations and fragments generated into one Swift module.",
    fields = {
        "schema": "Label of the apollo_schema these operations are generated against.",
        "module_name": "string: Swift module the generated code is compiled into.",
        "srcs": "depset[File]: .graphql files owned (generated) by this target.",
        "transitive_srcs": "depset[File]: srcs of this target and all of its deps. Fragments " +
                           "defined here are visible to dependents.",
    },
)

ApolloTestMocksInfo = provider(
    doc = "A module of generated test mocks, part of a base + features partition.",
    fields = {
        "schema": "Label of the apollo_schema.",
        "schema_info": "ApolloSchemaInfo of that schema, for the partition test's reference actions.",
        "module_name": "string: Swift module the mocks compile into (the `baseModule` of dependants).",
        "base": "Label of the base apollo_test_mocks, or None for the base itself.",
        "types": "list[string]: declared owned types (base) or extra includes (feature).",
        "exclude_types": "list[string]: base only, the feature-owned types.",
        "scope_files": "depset[File]: features only, the .graphql files that define the `referenced` scope.",
        "generated_tree": "File: the TestMocks tree artifact.",
        "build_target": "Label of the BUILD target declaring `types`, for the partition updater.",
    },
)
