"""Repository rules for Apollo iOS runtimes (see docs/MIGRATIONS.md).

A runtime is one Apollo iOS version, built from the upstream apollographql/apollo-ios
release under module names with an optional suffix (`ApolloAPI_v2`), so two
runtimes can be linked into one app. Code keeps writing `import ApolloAPI`; targets
on a suffixed runtime are compiled with `-module-alias ApolloAPI=ApolloAPI_v2`.
"""

APOLLO_MODULES = ["ApolloAPI", "Apollo", "ApolloTestSupport"]

SOURCE_URL_TEMPLATE = "https://github.com/apollographql/apollo-ios/archive/refs/tags/{version}.tar.gz"

def runtime_aliases(suffix, modules = APOLLO_MODULES):
    """`-module-alias` flags mapping each module to its suffixed name.

    Args:
        suffix: the runtime's module suffix; no flags when empty.
        modules: module names to alias.

    Returns:
        list of flags.
    """
    flags = []
    if suffix:
        for module in modules:
            flags += ["-module-alias", "%s=%s%s" % (module, module, suffix)]
    return flags

def runtime_defines(version):
    """`-D APOLLO_IOS_<major>`, for the rare shared code that must differ by version.

    Args:
        version: Apollo iOS version.

    Returns:
        list of flags.
    """
    return ["-DAPOLLO_IOS_" + version.split(".")[0]]

_RUNTIME_BUILD = """\
load("@build_bazel_rules_swift//swift:swift_library.bzl", "swift_library")

# Apollo iOS {version}, built from the upstream release by rules_apollo.
_COPTS = {copts}

swift_library(
    name = "ApolloAPI",
    srcs = glob(["Sources/ApolloAPI/**/*.swift"]),
    copts = _COPTS,
    module_name = "ApolloAPI{suffix}",
    package_name = "apollo-ios{suffix}",
    visibility = ["//visibility:public"],
)

swift_library(
    name = "Apollo",
    srcs = glob(["Sources/Apollo/**/*.swift"]),
    copts = _COPTS,
    module_name = "Apollo{suffix}",
    package_name = "apollo-ios{suffix}",
    visibility = ["//visibility:public"],
    deps = [":ApolloAPI"],
)

swift_library(
    name = "ApolloTestSupport",
    testonly = True,
    srcs = glob(["Sources/ApolloTestSupport/**/*.swift"]),
    copts = _COPTS,
    module_name = "ApolloTestSupport{suffix}",
    package_name = "apollo-ios{suffix}",
    visibility = ["//visibility:public"],
    deps = [
        ":Apollo",
        ":ApolloAPI",
    ],
)
"""

def _apollo_runtime_repo_impl(rctx):
    version = rctx.attr.version
    rctx.download_and_extract(
        url = [t.format(version = version) for t in rctx.attr.url_templates],
        sha256 = rctx.attr.sha256,
        stripPrefix = "apollo-ios-" + version,
    )

    # Apollo iOS 1.x is Swift 5 language mode; 2.x is Swift 6.
    swift_version = "5" if version.startswith("1.") else "6"
    copts = ["-swift-version", swift_version] + runtime_aliases(rctx.attr.suffix)
    rctx.file("BUILD.bazel", _RUNTIME_BUILD.format(
        version = version,
        suffix = rctx.attr.suffix,
        copts = repr(copts),
    ))

apollo_runtime_repo = repository_rule(
    implementation = _apollo_runtime_repo_impl,
    doc = "Builds one Apollo iOS runtime version under suffixed module names.",
    attrs = {
        "version": attr.string(mandatory = True),
        "suffix": attr.string(),
        "sha256": attr.string(mandatory = True),
        "url_templates": attr.string_list(default = [SOURCE_URL_TEMPLATE]),
    },
)

def _apollo_runtimes_hub_impl(rctx):
    entries = []
    for name, info in rctx.attr.runtimes.items():
        version, suffix = info.split("|")
        entries.append("""\
    "{name}": struct(
        name = "{name}",
        version = "{version}",
        suffix = "{suffix}",
        cli = Label("@apollo_runtime_{name}_cli//:cli"),
        apollo_api = Label("@apollo_runtime_{name}//:ApolloAPI"),
        apollo = Label("@apollo_runtime_{name}//:Apollo"),
        apollo_test_support = Label("@apollo_runtime_{name}//:ApolloTestSupport"),
    ),""".format(name = name, version = version, suffix = suffix))

    rctx.file("BUILD.bazel", 'exports_files(["defs.bzl"])\n')
    rctx.file("defs.bzl", """\
\"\"\"Apollo iOS runtimes declared with apollo.runtime(). Generated by rules_apollo.\"\"\"

RUNTIMES = {{
{entries}
}}
""".format(entries = "\n".join(entries)))

apollo_runtimes_hub = repository_rule(
    implementation = _apollo_runtimes_hub_impl,
    doc = "Exposes the declared runtimes to the rules_apollo macros as `RUNTIMES`.",
    attrs = {"runtimes": attr.string_dict(doc = "name -> 'version|suffix'")},
)
