"""Hands the CLI's tree artifact of generated Swift to `swift_library`.

rules_swift 4.2.0 compiles a directory (tree artifact) in `srcs` file by file:
each generated file gets its own object, as if it were listed individually. So
the CLI's output directory is used as is. Files that the user replaces are left
out by copying the directory without them.
"""

def generated_swift_sources(ctx, tree, exclude = []):
    """Returns the generated Swift sources in `tree` for a `swift_library`.

    Args:
        ctx: rule context.
        tree: tree artifact of generated .swift files.
        exclude: paths relative to `tree` to leave out (e.g. files the user replaces).

    Returns:
        File: `tree`, or a copy of it without `exclude`.
    """
    if not exclude:
        return tree

    filtered = ctx.actions.declare_directory(tree.basename + "_filtered")
    args = ctx.actions.args()
    args.add(tree.path)
    args.add(filtered.path)
    args.add_all(exclude)
    ctx.actions.run_shell(
        inputs = [tree],
        outputs = [filtered],
        arguments = [args],
        command = """\
set -eu
src="$1"; dst="$2"; shift 2
cp -RL "$src/." "$dst"
for path in "$@"; do rm -f "$dst/$path"; done
""",
        mnemonic = "ApolloFilterSources",
        progress_message = "Filtering generated Swift for %{label}",
    )
    return filtered

def module_placeholder(ctx):
    """Declares a Swift file with no code, so a module whose tree is empty compiles.

    A target can legitimately generate nothing (e.g. feature mocks whose types all
    belong to the base), and swiftc rejects a module without input files.

    Args:
        ctx: rule context.

    Returns:
        File
    """
    placeholder = ctx.actions.declare_file(ctx.label.name + "_Module.swift")
    ctx.actions.write(placeholder, "// @generated by rules_apollo for %s.\n" % ctx.label)
    return placeholder
