"""Generated by tools/update_versions.sh. Do not edit."""

APOLLO_CLI_REPO = "erneestoc/apollo-ios-dev"

# version -> { rust target triple -> sha256 of apollo-ios-cli-<triple>.tar.gz }
APOLLO_CLI_VERSIONS = {
    "1.15.1": {
        "aarch64-apple-darwin": "3c66c15229199f9742f30b81b98d8e3d5bd1dcd61a333c4fdc165da5a96f764b",
        "aarch64-unknown-linux-gnu": "c71793ebb515282e5665295facdb896a9805c42613eaadb83fb27397e5337046",
        "x86_64-unknown-linux-gnu": "c7e160c32c5cda3f10bd2e1ec304fa54856a40c54d4cee5025f98470c75db085",
    },
    "1.15.2": {
        "aarch64-apple-darwin": "e9058ac5fd64b9004a23190f9862c3a2b41287130db60b91415ab21fe0c97817",
        "aarch64-unknown-linux-gnu": "6a1884a18055f93b016c0b7626578cc924bb8610fdc3b55c2370e058778536e5",
        "x86_64-unknown-linux-gnu": "e12c841a765c9cfffbe5d54f656528455a929d96a465e1fa5d8f0c4c9db4738b",
    },
    "1.15.3": {
        "aarch64-apple-darwin": "5fd4d68ad9fe91d46c31472859043d1b6b9cc1f684bcdf49ea0bbe79a53a7b1a",
        "aarch64-unknown-linux-gnu": "dbfdd580921c52f9424a2a5aa6887c8ecd25a31a14bcb543e3883e9080b192c8",
        "x86_64-unknown-linux-gnu": "f87dd72b5ff0da33d25755799185fa40c339f9886bebba891e712d5b90687e02",
    },
    "1.16.0": {
        "aarch64-apple-darwin": "d6d1bf46afe2759533bbe72e938eabe301ac1c2a4690881ebcd5b53e7cad4258",
        "aarch64-unknown-linux-gnu": "16ea2c4e4cb9a7123b0f2333ca95a378fb5918ee9977c185dd10a2183a3ff76f",
        "x86_64-unknown-linux-gnu": "bcb16c861d03c7b030cf88ca01dbe1ba99f3d118d9a9220a9746827d6957479c",
    },
    "1.16.1": {
        "aarch64-apple-darwin": "263fd77eaec4d2992c54be98702a8b5134e09cf8133cec17c302f8e0bf1146a3",
        "aarch64-unknown-linux-gnu": "b05e85a82f2b75e76f7fa00f3ba80ee2822d82d76b649c4d9ec299d28030182f",
        "x86_64-unknown-linux-gnu": "6adc85faac4f283473235d33acdd1a61625da881fa03f2d01e241400e95a22fe",
    },
    "1.17.0": {
        "aarch64-apple-darwin": "633f909ed67f603e0dfe00a948c3ced276bfa5bd20c901cd81e98fbc5815b88b",
        "aarch64-unknown-linux-gnu": "1c00c76c23d0af4d2952c1da6ada0bc9e6d2407a6217185adcdc20f0251b62cc",
        "x86_64-unknown-linux-gnu": "597f9424e64c26ad7b5029de6950056e37be15c45f2a186ff02bc24251b5c138",
    },
    "1.18.0": {
        "aarch64-apple-darwin": "69b091e5afc0da81d883f36e24b554852577e24d75278dd6521dca11810d2044",
        "aarch64-unknown-linux-gnu": "94afc72e9bf111a6d4a141d7ab8c8a9c453020243e9a68c614b91d988d4e065a",
        "x86_64-unknown-linux-gnu": "a02cb3630800fcb2d733ba08caf01e769aedc2108e43b46373b07315ffaae1c7",
    },
    "1.19.0": {
        "aarch64-apple-darwin": "4911c22a43498f94ebbb4d16428f71175861fbea47058e684089f7e5a6789441",
        "aarch64-unknown-linux-gnu": "b1128ee0a2fe934ec04dd2ac38d149bcd218ae28a1243061aed88d23c1b6cb76",
        "x86_64-unknown-linux-gnu": "d27a40178c13eb5272113dcde49f405bba54885ea779881bffe39680912b58a3",
    },
    "1.20.0": {
        "aarch64-apple-darwin": "488e912282014b70a1a1de0f4bd80c76c7d28602ed81feb0b0de0dcbf7e7bc87",
        "aarch64-unknown-linux-gnu": "7535a587a727abb39bd5d87e3f4b32a866d6ed516180362ce16798d812de9ff0",
        "x86_64-unknown-linux-gnu": "49be38ac8efb93866ef38bb72361bbb5f2481ac6f382ef95c6f23421fb6954ab",
    },
    "1.21.0": {
        "aarch64-apple-darwin": "f7e7677a1429b503105fd31f1c1252dd81d147b8d5d3a5b9ed11d94124f18024",
        "aarch64-unknown-linux-gnu": "afaa4d9aa3f4ece87d5f38a5fe67d96bf33b5b842292b6abad057c12a76c2b26",
        "x86_64-unknown-linux-gnu": "d3c7f863ec5f8a074e1885d7364f8eb7c2e0946dcda9c8bf3fb8e0ec19823d9b",
    },
    "1.22.0": {
        "aarch64-apple-darwin": "dcb4c5e5f58f0c4409fafe190bb489a0b417f9b87ad8f340c85afcea408c7cc3",
        "aarch64-unknown-linux-gnu": "16129194098b3756c10fe3755f7734af89c60c3dea96d19d4a0f2f2344fd74d0",
        "x86_64-unknown-linux-gnu": "7a5b54eaad54772bb86de06237107e09b6d75166b19ff8cb714bb75943c981ce",
    },
    "1.23.0": {
        "aarch64-apple-darwin": "d7f0cac9b1cc285128b3b551dbbb282ee53e9568c14599f8aea635cdea4bd60a",
        "aarch64-unknown-linux-gnu": "069f53728f362522ad3d5cff19e2ca7cbc3c46f20ae0e0c0da3caf102538df58",
        "x86_64-unknown-linux-gnu": "100b7b812ca129524a5e54b3fa21579693032b2dc65c2cc94bbea2a2248ae7c6",
    },
    "1.24.0": {
        "aarch64-apple-darwin": "1854e26f8c5ade7c6ba3cf9b66d45b44e9fe6bcf96b6bf35b1fbaef2a6c221f0",
        "aarch64-unknown-linux-gnu": "c9f8a72f3d606bbe430f89c7b19ba6abeab3c9690f72158117879b33c48b2a68",
        "x86_64-unknown-linux-gnu": "d877c700ae8e1d617fc31215c65fe526e60152f80668431bd1766f05b9fce5d5",
    },
    "1.25.0": {
        "aarch64-apple-darwin": "826176fada909f70cb882eb68681c58e7483f1df166be7a6849457a9d9e639a1",
        "aarch64-unknown-linux-gnu": "b3399b1da60bd5601ca9ac34c087945d5b0fec41e2d01551e42fc4b29f1ba0fe",
        "x86_64-unknown-linux-gnu": "e2fc1807d892b4a15b65dd4bc55c5f187de7922c64cc76dc060fb18b1a72fd5b",
    },
    "1.25.1": {
        "aarch64-apple-darwin": "33ec1bf400a23e9cd36833ea9a74464c08c9d21a42cb0dbf7f5a7e330cb5cc3d",
        "aarch64-unknown-linux-gnu": "915fd90056e28e87bc40f79c034733b12f8815c3aea3ec748945a3566c65e21c",
        "x86_64-unknown-linux-gnu": "63f62ff0792fd9fbb81fea03e1ba1e8bc6ea440ae5717454c60884fd00afc6a4",
    },
    "1.25.2": {
        "aarch64-apple-darwin": "a39f94feb6c0c23dc085d84a65ee2348443b4277a99a06cc5c291ba297c786ad",
        "aarch64-unknown-linux-gnu": "2953d96ce26bd2d9880fd491b5a7e1c27ce421ef6667351980c5d86b0983495a",
        "x86_64-unknown-linux-gnu": "4d3b42cda49b0893b3a3dd7aec6ff8abecd87049a43411936b91c6ebce9571d7",
    },
    "1.25.3": {
        "aarch64-apple-darwin": "cbc63e997ccb505dcaebe7cbfe2e63716bd873f455cf976da80868cac006c931",
        "aarch64-unknown-linux-gnu": "a89d0f46197d80b2eb7d4bc1e9deb25b257cff5f590c06395e5e1ecfc9709d52",
        "x86_64-unknown-linux-gnu": "7fdcc3f1ca23f01d6768de6d238b1e824e8ab646f30b77e231d0bec5f009e4bc",
    },
    "1.25.4": {
        "aarch64-apple-darwin": "71d55b871cb62ce06923692c741c78c342a349d6402e84dbc1822429fc4c9ecb",
        "aarch64-unknown-linux-gnu": "cb3e8dbd73684db51f2c35251aac5744f4775a7f539a71341c36202a458cfd6d",
        "x86_64-unknown-linux-gnu": "4d839ab90a28dad28b5063bf6977d308243255f50868613fe8e1ffa165412c93",
    },
    "1.25.5": {
        "aarch64-apple-darwin": "2766ba647e77177ac502564ab73db91b0e2abb7c3430f42b1f24d158c22ad42d",
        "aarch64-unknown-linux-gnu": "0ae5f25e6779c63fff063a3a3bdc19fea766c8a3a88ae2cff5ad1eb3b244830c",
        "x86_64-unknown-linux-gnu": "921b39c9eec86af752c31f0938e1b52696b073b65660f95169e179f92f5d7502",
    },
    "1.25.6": {
        "aarch64-apple-darwin": "8a6b957780f2393d29036f61e3923c2c29a43a0adaf8606dc08e894c270a8596",
        "aarch64-unknown-linux-gnu": "a41f0cdc3e29c43c095ee02b8700d3d93e91eed03c6d96b79fffced051702455",
        "x86_64-unknown-linux-gnu": "e94d3087ec541e0cd370bb0f1c9ec28b0e450d65bc90bf814fe995970a14a229",
    },
    "1.25.7": {
        "aarch64-apple-darwin": "49dc3ddf3d4c086bb07380904fc42a2935db139636c9f4b1acc613461b4994ea",
        "aarch64-unknown-linux-gnu": "e1f728ae1467a75e822a77bf93b2fac3b99136958cb6fb0ec5d0d94652948abe",
        "x86_64-unknown-linux-gnu": "7eb086e1d69b6139176eb8a8df8cc21c8c81d9aa144844701743e20b6dab9b1a",
    },
    "2.0.0": {
        "aarch64-apple-darwin": "24c6e1de81ee82ceaf721780a416284882510896db70ab48abb6ea9f2bd8a88b",
        "aarch64-unknown-linux-gnu": "b281e0e8dc07f2b6f1f614116739ad2b7ec53290a8cc0df100a351ff42054488",
        "x86_64-unknown-linux-gnu": "841e0a522b73b2985b37145f7deaeebbb2991a2f6b5e20e9b745c6ba8aa8663c",
    },
    "2.0.1": {
        "aarch64-apple-darwin": "feb780ceb363406c098014380ebc3b551fcf790a4eff9a4c99822ae12d7481a1",
        "aarch64-unknown-linux-gnu": "9fbbc39fda5e22803325ccb98f538e7f6ae0c1a75b8ca9d0bf2761f5bb5bf3bd",
        "x86_64-unknown-linux-gnu": "18e474529c893028b7c96e41728adfcfe3739299d326e0cf17ef71fc7d300ea5",
    },
    "2.0.2": {
        "aarch64-apple-darwin": "2a05891a8a2602f5396ecca7560c790e51db04749ad1396936d1d37fd0da9d52",
        "aarch64-unknown-linux-gnu": "b8b3f376db286f083d45e85711ce8f44f9877f2023b1249039cb5e1c4a56cca8",
        "x86_64-unknown-linux-gnu": "198797ac3a6c7c87b69cc24298a4e319bc99cf6ea903e616503711586f3d9af9",
    },
    "2.0.3": {
        "aarch64-apple-darwin": "02f21b290e6dc8a18994257bf9de50f97c08a7447f3bf2f0636bd1f63c5d18d1",
        "aarch64-unknown-linux-gnu": "bbc3fe8d3f8eb960a0a57678c1bc1345b56c373e4cfdb49a3d7c10dde5cd10d9",
        "x86_64-unknown-linux-gnu": "b301e6945f061e205e301305acc93f61b7cc0fd3761357236cfcc2bfde41ad44",
    },
    "2.0.4": {
        "aarch64-apple-darwin": "a906153e68e3a7594d26b73d9feb07fa7a80f7b48564710d0035301518165f19",
        "aarch64-unknown-linux-gnu": "418dec1d651fff1f49026f830d291e19d7f4d53d1948a8fdf0f1826fcff3b0fc",
        "x86_64-unknown-linux-gnu": "f7afee14e6c83528c8d15bdf7db93e7a5800d8d88a7d267be13f20b7d714cebc",
    },
    "2.0.5": {
        "aarch64-apple-darwin": "5e9b411374ac553e617ba625abdb7747897391d3c9dda3fd715efc8ae2f9b1e8",
        "aarch64-unknown-linux-gnu": "ddf2595d5c4503ea5fe74fbfd5c190a6718cd6db46137fa4d2c5b585b61ee843",
        "x86_64-unknown-linux-gnu": "6adc5788cd42205ff6b66e372bead899e309b70a31497a1964ef6dbe92849568",
    },
    "2.0.6": {
        "aarch64-apple-darwin": "52ac5500f7c11d5959c0122a527369ae33eb813014123168b8abb7d85bce6f9b",
        "aarch64-unknown-linux-gnu": "6bd9ebbc35ff9658ee21c623093f82bf23a075b3d7473510f88f0365ecbf2609",
        "x86_64-unknown-linux-gnu": "bd8a64ba872782d7bfa8f14536b6ab15332585dbb73dd97a1faf245da6fd0615",
    },
    "2.1.0": {
        "aarch64-apple-darwin": "ccf30b17be45cd5a4375dc0ccbe92ee87a6092d1505f1cbc1457537a2b34383c",
        "aarch64-unknown-linux-gnu": "ff0560b964caa49ab0e5900aa9b556dab7046f4871794e7257a1013d821b109f",
        "x86_64-unknown-linux-gnu": "2d73608472654048c93b22b759a4f06d2840c73b34ae04c5d9df3a350ace5942",
    },
    "2.1.1": {
        "aarch64-apple-darwin": "13210c13cc91a99111b7cf7d253a13d27ce14202ceba7adb553926889561f47c",
        "aarch64-unknown-linux-gnu": "7130596d18de80db5d82165661d26ff525401b84a53af43ecf0e75906f8d731c",
        "x86_64-unknown-linux-gnu": "772d6954ed6934e3c0a5269412a16312cf53beb26cbc8837e4c46032fec35ed3",
    },
    "2.1.2": {
        "aarch64-apple-darwin": "03f0945e58bf9d59b072515f3a4048b633a9ed4baddbdb9793bb1e89a930fe05",
        "aarch64-unknown-linux-gnu": "627aeada8c3b2c69ec3b5efd1d3625fc1365ce78e0699dd1754a0a2aa201df2d",
        "x86_64-unknown-linux-gnu": "eb6bd21144fa9f85ba756444876bda151970b5fad85b488e95ec769e3fd03c4c",
    },
    "2.2.0": {
        "aarch64-apple-darwin": "feb883bcb6793fa36183347cd98524c57ed6f5792422c0207d91a2ab49a8abd7",
        "aarch64-unknown-linux-gnu": "376e34b80df35ceda07e2a2edd42949032fd24a273263cebf9de99d522275de4",
        "x86_64-unknown-linux-gnu": "9a1dd61899f582df41f5bd45803a20e67e73421e67cb32eafb234b5b856e5d16",
    },
    "2.3.0": {
        "aarch64-apple-darwin": "2e61c60e0adc5c47b0e17a23edaa57e25c32467480fd5e3f6b4a4deb456aeb7a",
        "aarch64-unknown-linux-gnu": "ad2f64c5b32542f2782049a1c3b82eb1bd3decce0694422d1c2ba8d8850c982b",
        "x86_64-unknown-linux-gnu": "227030ab6610fe4fb67a3028d4f913f9cad632c964821bc2d3eb1d3586d41fe3",
    },
    "2.4.0": {
        "aarch64-apple-darwin": "dee5884823f7faf6f30568186f3e290f73bb84f256029ffbae2ab43dc8f65a86",
        "aarch64-unknown-linux-gnu": "9b0179b0013b41c27a7966b2753176f4029c9a47e4503c6ae06a66d16060551f",
        "x86_64-unknown-linux-gnu": "77dff4375dd7a2139ed6b296e232c9465e3632211147845a19fbba61fd92f852",
    },
}
